export const meta = {
  slug: "2026-06-16-sap-s4hana-aws-migration-senior-delivery-consultant-interview-questions",
  title: "SAP S/4HANA AWS Migration Interview Questions and Answers — Senior Delivery Consultant Round",
  description: "55+ real SAP S/4HANA AWS migration interview questions with technical answers. Covers SUM DMO, HANA HA, DR setup, RISE with SAP, BTP integration, GenAI, and cloud architecture. Based on a real Senior Delivery Consultant interview round.",
  date: "2026-06-16",
  keywords: "SAP S/4HANA migration interview questions, SAP AWS migration interview, Senior SAP Delivery Consultant interview, SUM DMO interview questions, HANA HA DR setup interview, RISE with SAP interview questions, SAP BTP integration interview, HANA System Replication interview, SAP brownfield migration AWS, SAP greenfield implementation interview, AWS Backint Agent SAP, SAP SWPM migration, HANA tenant copy interview, SAP DR setup interview questions, SAP ProServe interview questions",
  layout: "interview-post",
  faqs: [
    {
      q: "What is SUM DMO in SAP migration?",
      a: "SUM — Software Update Manager with Database Migration Option — is the SAP-provided tool that migrates ECC from Oracle, SQL Server, or DB2 to HANA while simultaneously converting the application to S/4HANA in a single downtime window.",
    },
    {
      q: "What is the difference between brownfield and greenfield S/4HANA migration?",
      a: "Brownfield converts existing ECC in place using SUM DMO — preserving all configuration, data, and custom code. Greenfield starts fresh on S/4HANA using SAP Best Practices. Brownfield is faster with less disruption. Greenfield allows process redesign from scratch.",
    },
    {
      q: "What is RISE with SAP on AWS?",
      a: "RISE with SAP is SAP's subscription model where SAP operates S/4HANA Cloud Private Edition in SAP-managed AWS accounts. SAP manages infrastructure, OS, HANA, and upgrade execution. Customer owns preparation, connectivity, integration, data migration, and validation.",
    },
    {
      q: "How does HANA System Replication work for HA?",
      a: "HSR replicates HANA persistence — data volumes and log volumes — from primary to secondary node continuously. Synchronous mode means primary waits for secondary acknowledgment before committing transactions — zero data loss. Pacemaker cluster resource manager executes automatic failover when primary fails — typically 47 to 90 seconds end to end.",
    },
    {
      q: "What is Downtime Optimized DMO?",
      a: "Downtime Optimized DMO pre-migrates bulk data to the AWS target while source ECC stays live. Production downtime is reduced to only the final delta sync plus S/4HANA conversion — 4 to 8 hours instead of 20 to 35 hours for standard DMO.",
    },
    {
      q: "What is Clean Core in S/4HANA?",
      a: "Clean Core means no customer custom logic lives inside the SAP core software components. All custom logic must use SAP-published extension points — in-app via ABAP RAP with released APIs or side-by-side extensions on BTP using CAP. This ensures upgrade safety — no conflicts with SAP support packages.",
    },
    {
      q: "What is the DURATION.XML file in SUM?",
      a: "DURATION.XML is generated by SUM in the SUMLOG directory after every run. It records every phase with start timestamp, end timestamp, duration in seconds, status, and retry count. Used to identify which phases consumed the most time and how much was dead time from retry cycles versus actual processing — drives optimization between dress rehearsal runs.",
    },
    {
      q: "What is SAP BTP Integration Suite?",
      a: "BTP — Business Technology Platform — Integration Suite is SAP's cloud-native integration middleware replacing SAP PI/PO. It uses iFlow-based orchestration to connect S/4HANA to AWS services — API Gateway, EventBridge, Lambda, Bedrock — and to other SAP and non-SAP systems.",
    },
    {
      q: "How do you set up DR for SAP on AWS?",
      a: "DR uses multi-tier HANA System Replication — sync HA replication within the production region, async DR replication to a second AWS region. Application servers use Pilot Light model — HANA EC2 running in DR region, application servers launched from pre-built AMIs via CloudFormation on DR declaration. EFS Replication keeps /sapmnt synchronized between regions continuously.",
    },
    {
      q: "What are the prerequisites for DMO4 — SUM with System Move?",
      a: "SUM 2.0 SP15 or higher, source ECC minimum EHP5, SAP kernel 7.49+, source must be Unicode, source database minimum version, target must be SAP-certified AWS instance, minimum 1 Gbps dedicated Direct Connect bandwidth, MTU 9001 jumbo frames on ENI, 20% free disk on source for replication log, all add-ons compatible with target S/4HANA release, Business Partner migration complete.",
    },
  ],
} as const;
