import type { Metadata } from 'next';
import KnowledgeGuidePage from '@/components/KnowledgeGuidePage';
import { landingPageMetadata } from '@/lib/site-seo';

export const metadata: Metadata = landingPageMetadata({
  title: 'Hugging Face RAG & Embeddings Guide — Sentence Transformers, Reranking, Vector Search | Proxy Tech Support',
  description: 'Practical guide to building RAG on Hugging Face: embeddings with Sentence Transformers, bi-encoder vs cross-encoder reranking, chunking, vector stores, hybrid search, TEI serving, and evaluation.',
  canonical: 'https://proxytechsupport.com/hugging-face-rag-embeddings-guide/',
});

export default function Page() {
  return (
    <KnowledgeGuidePage
      h1="Hugging Face RAG & Embeddings Guide: Sentence Transformers, Reranking, and Retrieval Debugging"
      intro="Retrieval-augmented generation lives or dies on retrieval quality, and most of that quality comes from how you embed, chunk, and rerank your data. This guide walks through building production RAG on the Hugging Face stack — from Sentence Transformers embeddings and cross-encoder reranking to hybrid search, TEI serving, and evaluation."
      sections={[
        { heading: 'Why Embeddings Are the Foundation of RAG', body: 'A RAG system can only generate answers from the passages it retrieves, so the embedding model is the single most important choice in the pipeline. Embeddings map text into a vector space where semantic similarity becomes geometric proximity, letting you find relevant passages by nearest-neighbour search. Sentence Transformers v5 is the standard Hugging Face library for producing these embeddings, exposing bi-encoders, cross-encoders, sparse encoders, and multi-vector models behind a consistent API. Choosing a model that matches your domain, language, and latency budget matters more than any prompt-engineering trick downstream.' },
        { heading: 'Bi-Encoders vs Cross-Encoders and Reranking', body: 'The two-stage retrieve-then-rerank pattern is the workhorse of modern RAG. Bi-encoders embed the query and each document independently, so document vectors can be precomputed and searched with an ANN index at scale. Cross-encoders instead take the query and a candidate document together and output a single relevance score, which is far more accurate but too slow to run over a whole corpus.', bullets: ['Use a bi-encoder for first-stage retrieval to pull the top 50-100 candidates from millions of documents', 'Use a Sentence Transformers CrossEncoder to rerank that shortlist down to the top 3-10 passages fed to the LLM', 'Reranking typically produces the largest single quality jump in a RAG pipeline for modest added latency', 'Multi-vector and ColBERT-style late-interaction models offer a middle ground between speed and cross-encoder accuracy'] },
        { heading: 'Chunking Strategy', body: 'Chunking determines what a single retrievable unit contains, and bad chunking silently caps retrieval quality no matter how good your model is. Chunks that are too large dilute the embedding signal and waste context window; chunks that are too small lose the surrounding context needed to answer a question. Practical strategies include splitting on semantic boundaries such as headings and paragraphs, keeping chunks in the 200-500 token range, adding overlap between adjacent chunks, and preserving metadata like section titles and source URLs for filtering and citation. Test chunking empirically against your evaluation set rather than assuming a default works.' },
        { heading: 'Vector Stores and Hybrid Search', body: 'Once you have embeddings you need an index to search them, and the choice depends on scale and infrastructure. FAISS is common for in-process and prototype workloads, while managed and self-hosted vector databases such as Qdrant, Weaviate, Milvus, and pgvector handle larger corpora with filtering and persistence. Dense embeddings excel at semantic matching but can miss exact keyword matches like part numbers or rare entities, so hybrid search combines dense vectors with sparse lexical retrieval (BM25 or learned sparse encoders) and fuses the results, often with reciprocal rank fusion. Hybrid retrieval plus reranking is the most reliable recipe for high-precision RAG.' },
        { heading: 'Serving Embeddings with TEI', body: 'In production you want embedding inference decoupled from your application and running on optimised infrastructure. Text Embeddings Inference (TEI) is Hugging Face\'s dedicated server for embedding and reranking models, offering token-based dynamic batching, ONNX and optimised kernels, and support for bi-encoders, sparse encoders, and cross-encoder rerankers behind an HTTP API. Running embeddings and reranking through TEI gives you consistent low latency under concurrent load, keeps the model out of your application memory footprint, and lets you scale the embedding tier independently. You can self-host TEI or use Hugging Face Inference Endpoints for a managed deployment.' },
        { heading: 'Debugging Retrieval Collapse', body: 'The most common RAG failure is retrieval that returns plausible-looking but irrelevant passages, causing the LLM to hallucinate or refuse. Diagnose it by inspecting the retrieved chunks directly before blaming the generation model, since the fault is almost always upstream.', bullets: ['Query-document mismatch: the embedding model was trained for symmetric similarity but your queries are short questions and documents are long passages (use an asymmetric or query-tuned model)', 'Broken normalisation or a distance-metric mismatch (cosine vs dot product vs L2) between indexing and querying', 'Chunks too large so the relevant sentence is drowned out in the averaged embedding', 'Missing reranking, so mediocre first-stage candidates reach the LLM unchallenged', 'Domain drift where a general-purpose model cannot separate near-identical technical documents and needs fine-tuning'] },
        { heading: 'Agentic RAG', body: 'Static single-shot retrieval struggles with multi-hop questions, ambiguous queries, and tasks that need tool use, which is where agentic RAG comes in. Instead of retrieving once and generating, an agent can reformulate the query, retrieve iteratively, decide when it has enough evidence, and call additional tools. On the Hugging Face stack this is commonly built with smolagents, where a CodeAgent or ToolCallingAgent treats retrieval as one tool among several and orchestrates multi-step reasoning. Agentic RAG improves answer quality on complex questions but adds latency and cost, so it should be reserved for workloads that genuinely need multi-step retrieval rather than applied everywhere.' },
        { heading: 'Evaluating a RAG Pipeline', body: 'You cannot improve retrieval you do not measure, so building an evaluation set is the highest-leverage early investment. Separate retrieval metrics from generation metrics: measure retrieval with recall@k, precision@k, and mean reciprocal rank against known-relevant passages, and measure generation with faithfulness (is the answer grounded in retrieved context) and answer relevance. Assemble a representative set of real questions with labelled relevant chunks, then run controlled experiments changing one variable at a time — embedding model, chunk size, reranker, or top-k. This empirical loop is what turns a demo-quality RAG into a reliable production system.' },
      ]}
      relatedLinks={[
        { href: '/hugging-face-proxy-job-support/', label: 'Hugging Face Job Support Hub' },
        { href: '/huggingface-semantic-search-job-support/', label: 'Semantic Search Job Support' },
        { href: '/huggingface-reranking-job-support/', label: 'Reranking Job Support' },
        { href: '/huggingface-embeddings-job-support/', label: 'Embeddings Job Support' },
        { href: '/huggingface-agentic-rag-job-support/', label: 'Agentic RAG Job Support' },
        { href: '/sentence-transformers-proxy-interview-support/', label: 'Sentence Transformers Interview Support' },
      ]}
      relatedGuides={[
        { href: '/hugging-face-rag-embeddings-guide/', label: 'Hugging Face RAG & Embeddings Guide' },
        { href: '/rag-agentic-ai-job-support-guide/', label: 'RAG & Agentic AI Job Support Guide' },
        { href: '/hugging-face-inference-deployment-guide/', label: 'Hugging Face Inference & Deployment Guide' },
        { href: '/hugging-face-job-support-guide/', label: 'Hugging Face Job Support Guide' },
      ]}
      faqs={[
        { q: 'What is the difference between a bi-encoder and a cross-encoder in RAG?', a: 'A bi-encoder embeds the query and each document separately so document vectors can be precomputed and searched at scale, making it ideal for first-stage retrieval. A cross-encoder scores a query and document together for much higher accuracy but cannot scale to a full corpus, so it is used to rerank a small shortlist of candidates.' },
        { q: 'Which embedding model should I use with Sentence Transformers?', a: 'Pick based on your domain, language coverage, latency budget, and whether your queries and documents are asymmetric. Start from a strong general-purpose model on the MTEB leaderboard, validate it against your own evaluation set, and fine-tune only if a general model cannot separate near-identical documents in your domain.' },
        { q: 'How do I fix a RAG system that retrieves irrelevant passages?', a: 'Inspect the retrieved chunks before blaming the LLM. The usual causes are a query-document symmetry mismatch, a distance-metric or normalisation bug between indexing and querying, chunks that are too large, or missing reranking. Adding a cross-encoder reranker and fixing chunk size resolves most retrieval-collapse cases.' },
        { q: 'What is hybrid search and when do I need it?', a: 'Hybrid search combines dense embedding retrieval with sparse lexical retrieval like BM25 and fuses the results, often with reciprocal rank fusion. You need it when exact keyword matches matter — part numbers, error codes, rare entities — because pure dense retrieval can miss literal terms that lexical search catches.' },
        { q: 'How do I serve Hugging Face embeddings in production?', a: 'Use Text Embeddings Inference (TEI), the dedicated Hugging Face server for embedding and reranking models. It provides dynamic batching and optimised kernels behind an HTTP API, lets you scale the embedding tier independently of your application, and can run self-hosted or on managed Inference Endpoints.' },
      ]}
      ctaHref="/huggingface-semantic-search-job-support/"
      ctaLabel="Get RAG & Embeddings Support"
    />
  );
}
