/** Auto-generated by scripts/migrate-md-to-blog-articles.mjs — edit article folders under content/blog-articles only. */

import Article_rag_aimlops_retrieval_augmented_generation_guide from './rag-aimlops-retrieval-augmented-generation-guide/Article';
import { meta as meta_rag_aimlops_retrieval_augmented_generation_guide } from './rag-aimlops-retrieval-augmented-generation-guide/meta';
import Article_interview_proxy_trends_2026 from './interview-proxy-trends-2026/Article';
import { meta as meta_interview_proxy_trends_2026 } from './interview-proxy-trends-2026/meta';
import Article_usa_tech_job_market_2026_in_demand_skills_roles from './usa-tech-job-market-2026-in-demand-skills-roles/Article';
import { meta as meta_usa_tech_job_market_2026_in_demand_skills_roles } from './usa-tech-job-market-2026-in-demand-skills-roles/meta';
import Article_proxy_job_support_interview_support_usa_uk_canada_australia from './proxy-job-support-interview-support-usa-uk-canada-australia/Article';
import { meta as meta_proxy_job_support_interview_support_usa_uk_canada_australia } from './proxy-job-support-interview-support-usa-uk-canada-australia/meta';
import Article_qa_automation_job_support_proxy_usa_uk_canada_australia from './qa-automation-job-support-proxy-usa-uk-canada-australia/Article';
import { meta as meta_qa_automation_job_support_proxy_usa_uk_canada_australia } from './qa-automation-job-support-proxy-usa-uk-canada-australia/meta';
import Article_it_job_support_proxy_australia_austria from './it-job-support-proxy-australia-austria/Article';
import { meta as meta_it_job_support_proxy_australia_austria } from './it-job-support-proxy-australia-austria/meta';
import Article_real_time_it_job_support_interview_proxy_usa_uk_canada_australia from './real-time-it-job-support-interview-proxy-usa-uk-canada-australia/Article';
import { meta as meta_real_time_it_job_support_interview_proxy_usa_uk_canada_australia } from './real-time-it-job-support-interview-proxy-usa-uk-canada-australia/meta';
import Article_dotnet_job_support_canada from './dotnet-job-support-canada/Article';
import { meta as meta_dotnet_job_support_canada } from './dotnet-job-support-canada/meta';
import Article_data_engineer_python_job_support from './data-engineer-python-job-support/Article';
import { meta as meta_data_engineer_python_job_support } from './data-engineer-python-job-support/meta';
import Article_dotnet_job_support_realtime_usa_uk from './dotnet-job-support-realtime-usa-uk/Article';
import { meta as meta_dotnet_job_support_realtime_usa_uk } from './dotnet-job-support-realtime-usa-uk/meta';
import Article_real_time_job_support_guide from './real-time-job-support-guide/Article';
import { meta as meta_real_time_job_support_guide } from './real-time-job-support-guide/meta';
import Article_angular_job_support_guide from './angular-job-support-guide/Article';
import { meta as meta_angular_job_support_guide } from './angular-job-support-guide/meta';
import Article_complete_guide_proxy_job_support_interview_assistance_all_technologies from './complete-guide-proxy-job-support-interview-assistance-all-technologies/Article';
import { meta as meta_complete_guide_proxy_job_support_interview_assistance_all_technologies } from './complete-guide-proxy-job-support-interview-assistance-all-technologies/meta';
import Article_ai_ml_job_support from './ai-ml-job-support/Article';
import { meta as meta_ai_ml_job_support } from './ai-ml-job-support/meta';
import Article_backend_enterprise_job_support from './backend-enterprise-job-support/Article';
import { meta as meta_backend_enterprise_job_support } from './backend-enterprise-job-support/meta';
import Article_cloud_technologies_job_support from './cloud-technologies-job-support/Article';
import { meta as meta_cloud_technologies_job_support } from './cloud-technologies-job-support/meta';
import Article_cybersecurity_job_support from './cybersecurity-job-support/Article';
import { meta as meta_cybersecurity_job_support } from './cybersecurity-job-support/meta';
import Article_databases_data_platforms_job_support from './databases-data-platforms-job-support/Article';
import { meta as meta_databases_data_platforms_job_support } from './databases-data-platforms-job-support/meta';
import Article_digital_analytics_job_support from './digital-analytics-job-support/Article';
import { meta as meta_digital_analytics_job_support } from './digital-analytics-job-support/meta';
import Article_frontend_fullstack_job_support from './frontend-fullstack-job-support/Article';
import { meta as meta_frontend_fullstack_job_support } from './frontend-fullstack-job-support/meta';
import Article_java_technologies_job_support from './java-technologies-job-support/Article';
import { meta as meta_java_technologies_job_support } from './java-technologies-job-support/meta';
import Article_testing_quality_engineering_job_support from './testing-quality-engineering-job-support/Article';
import { meta as meta_testing_quality_engineering_job_support } from './testing-quality-engineering-job-support/meta';
import Article_proxy_interview_support_job_support_global from './proxy-interview-support-job-support-global/Article';
import { meta as meta_proxy_interview_support_job_support_global } from './proxy-interview-support-job-support-global/meta';
import Article_job_support_interview_proxy_from_india from './job-support-interview-proxy-from-india/Article';
import { meta as meta_job_support_interview_proxy_from_india } from './job-support-interview-proxy-from-india/meta';
import Article_angular_job_support from './angular-job-support/Article';
import { meta as meta_angular_job_support } from './angular-job-support/meta';
import Article_aws_job_support from './aws-job-support/Article';
import { meta as meta_aws_job_support } from './aws-job-support/meta';
import Article_devops_job_support from './devops-job-support/Article';
import { meta as meta_devops_job_support } from './devops-job-support/meta';
import Article_dotnet_job_support from './dotnet-job-support/Article';
import { meta as meta_dotnet_job_support } from './dotnet-job-support/meta';
import Article_java_job_support from './java-job-support/Article';
import { meta as meta_java_job_support } from './java-job-support/meta';
import Article_node_job_support from './node-job-support/Article';
import { meta as meta_node_job_support } from './node-job-support/meta';
import Article_python_job_support from './python-job-support/Article';
import { meta as meta_python_job_support } from './python-job-support/meta';
import Article_react_job_support from './react-job-support/Article';
import { meta as meta_react_job_support } from './react-job-support/meta';
import Article_react_native_job_support from './react-native-job-support/Article';
import { meta as meta_react_native_job_support } from './react-native-job-support/meta';
import Article_real_time_it_job_support_benefits from './real-time-it-job-support-benefits/Article';
import { meta as meta_real_time_it_job_support_benefits } from './real-time-it-job-support-benefits/meta';
import Article_react_interview_proxy_guide from './react-interview-proxy-guide/Article';
import { meta as meta_react_interview_proxy_guide } from './react-interview-proxy-guide/meta';
import Article_interview_mentoring_for_it_professionals from './interview-mentoring-for-it-professionals/Article';
import { meta as meta_interview_mentoring_for_it_professionals } from './interview-mentoring-for-it-professionals/meta';
import Article_resume_linkedin_optimization_for_developers from './resume-linkedin-optimization-for-developers/Article';
import { meta as meta_resume_linkedin_optimization_for_developers } from './resume-linkedin-optimization-for-developers/meta';
import Article_ai_ml_data_science_proxy_job_support from './ai-ml-data-science-proxy-job-support/Article';
import { meta as meta_ai_ml_data_science_proxy_job_support } from './ai-ml-data-science-proxy-job-support/meta';

export const blogArticleEntries = [
  { meta: meta_rag_aimlops_retrieval_augmented_generation_guide, Article: Article_rag_aimlops_retrieval_augmented_generation_guide },
  { meta: meta_interview_proxy_trends_2026, Article: Article_interview_proxy_trends_2026 },
  { meta: meta_usa_tech_job_market_2026_in_demand_skills_roles, Article: Article_usa_tech_job_market_2026_in_demand_skills_roles },
  { meta: meta_proxy_job_support_interview_support_usa_uk_canada_australia, Article: Article_proxy_job_support_interview_support_usa_uk_canada_australia },
  { meta: meta_qa_automation_job_support_proxy_usa_uk_canada_australia, Article: Article_qa_automation_job_support_proxy_usa_uk_canada_australia },
  { meta: meta_it_job_support_proxy_australia_austria, Article: Article_it_job_support_proxy_australia_austria },
  { meta: meta_real_time_it_job_support_interview_proxy_usa_uk_canada_australia, Article: Article_real_time_it_job_support_interview_proxy_usa_uk_canada_australia },
  { meta: meta_dotnet_job_support_canada, Article: Article_dotnet_job_support_canada },
  { meta: meta_data_engineer_python_job_support, Article: Article_data_engineer_python_job_support },
  { meta: meta_dotnet_job_support_realtime_usa_uk, Article: Article_dotnet_job_support_realtime_usa_uk },
  { meta: meta_real_time_job_support_guide, Article: Article_real_time_job_support_guide },
  { meta: meta_angular_job_support_guide, Article: Article_angular_job_support_guide },
  { meta: meta_complete_guide_proxy_job_support_interview_assistance_all_technologies, Article: Article_complete_guide_proxy_job_support_interview_assistance_all_technologies },
  { meta: meta_ai_ml_job_support, Article: Article_ai_ml_job_support },
  { meta: meta_backend_enterprise_job_support, Article: Article_backend_enterprise_job_support },
  { meta: meta_cloud_technologies_job_support, Article: Article_cloud_technologies_job_support },
  { meta: meta_cybersecurity_job_support, Article: Article_cybersecurity_job_support },
  { meta: meta_databases_data_platforms_job_support, Article: Article_databases_data_platforms_job_support },
  { meta: meta_digital_analytics_job_support, Article: Article_digital_analytics_job_support },
  { meta: meta_frontend_fullstack_job_support, Article: Article_frontend_fullstack_job_support },
  { meta: meta_java_technologies_job_support, Article: Article_java_technologies_job_support },
  { meta: meta_testing_quality_engineering_job_support, Article: Article_testing_quality_engineering_job_support },
  { meta: meta_proxy_interview_support_job_support_global, Article: Article_proxy_interview_support_job_support_global },
  { meta: meta_job_support_interview_proxy_from_india, Article: Article_job_support_interview_proxy_from_india },
  { meta: meta_angular_job_support, Article: Article_angular_job_support },
  { meta: meta_aws_job_support, Article: Article_aws_job_support },
  { meta: meta_devops_job_support, Article: Article_devops_job_support },
  { meta: meta_dotnet_job_support, Article: Article_dotnet_job_support },
  { meta: meta_java_job_support, Article: Article_java_job_support },
  { meta: meta_node_job_support, Article: Article_node_job_support },
  { meta: meta_python_job_support, Article: Article_python_job_support },
  { meta: meta_react_job_support, Article: Article_react_job_support },
  { meta: meta_react_native_job_support, Article: Article_react_native_job_support },
  { meta: meta_real_time_it_job_support_benefits, Article: Article_real_time_it_job_support_benefits },
  { meta: meta_react_interview_proxy_guide, Article: Article_react_interview_proxy_guide },
  { meta: meta_interview_mentoring_for_it_professionals, Article: Article_interview_mentoring_for_it_professionals },
  { meta: meta_resume_linkedin_optimization_for_developers, Article: Article_resume_linkedin_optimization_for_developers },
  { meta: meta_ai_ml_data_science_proxy_job_support, Article: Article_ai_ml_data_science_proxy_job_support },
] as const;
