/** Auto-generated by scripts/migrate-md-to-interview-articles.mjs — edit folders under content/interview-articles only. */

import Article_2026_06_11_senior_cloud_engineer_aws_migration_finance_interview_questions from './2026-06-11-senior-cloud-engineer-aws-migration-finance-interview-questions/Article';
import { meta as meta_2026_06_11_senior_cloud_engineer_aws_migration_finance_interview_questions } from './2026-06-11-senior-cloud-engineer-aws-migration-finance-interview-questions/meta';
import Article_2026_06_02_senior_ai_ml_engineer_interview_questions_recommendation_systems from './2026-06-02-senior-ai-ml-engineer-interview-questions-recommendation-systems/Article';
import { meta as meta_2026_06_02_senior_ai_ml_engineer_interview_questions_recommendation_systems } from './2026-06-02-senior-ai-ml-engineer-interview-questions-recommendation-systems/meta';
import Article_2026_05_27_ai_technical_lead_interview_questions_rag_llm_financial_services_compliance from './2026-05-27-ai-technical-lead-interview-questions-rag-llm-financial-services-compliance/Article';
import { meta as meta_2026_05_27_ai_technical_lead_interview_questions_rag_llm_financial_services_compliance } from './2026-05-27-ai-technical-lead-interview-questions-rag-llm-financial-services-compliance/meta';
import Article_2026_05_06_real_security_engineer_interview_questions_cloud_security_devsecops_usa from './2026-05-06-real-security-engineer-interview-questions-cloud-security-devsecops-usa/Article';
import { meta as meta_2026_05_06_real_security_engineer_interview_questions_cloud_security_devsecops_usa } from './2026-05-06-real-security-engineer-interview-questions-cloud-security-devsecops-usa/meta';
import Article_2026_05_06_real_azure_architect_interview_questions_solutions_architect_usa from './2026-05-06-real-azure-architect-interview-questions-solutions-architect-usa/Article';
import { meta as meta_2026_05_06_real_azure_architect_interview_questions_solutions_architect_usa } from './2026-05-06-real-azure-architect-interview-questions-solutions-architect-usa/meta';
import Article_2026_05_06_real_ai_engineer_interview_questions_llm_agents_rag_system_design_usa from './2026-05-06-real-ai-engineer-interview-questions-llm-agents-rag-system-design-usa/Article';
import { meta as meta_2026_05_06_real_ai_engineer_interview_questions_llm_agents_rag_system_design_usa } from './2026-05-06-real-ai-engineer-interview-questions-llm-agents-rag-system-design-usa/meta';
import Article_2026_04_30_real_enterprise_ai_ml_engineer_interview_questions_rag_llm_genai_mlops from './2026-04-30-real-enterprise-ai-ml-engineer-interview-questions-rag-llm-genai-mlops/Article';
import { meta as meta_2026_04_30_real_enterprise_ai_ml_engineer_interview_questions_rag_llm_genai_mlops } from './2026-04-30-real-enterprise-ai-ml-engineer-interview-questions-rag-llm-genai-mlops/meta';
import Article_2026_04_25_real_devops_cloud_engineer_interview_questions_aws_kubernetes_helm_cicd_gitops from './2026-04-25-real-devops-cloud-engineer-interview-questions-aws-kubernetes-helm-cicd-gitops/Article';
import { meta as meta_2026_04_25_real_devops_cloud_engineer_interview_questions_aws_kubernetes_helm_cicd_gitops } from './2026-04-25-real-devops-cloud-engineer-interview-questions-aws-kubernetes-helm-cicd-gitops/meta';
import Article_2026_04_20_real_sap_abap_interview_questions_otc_pricing_odata_btp from './2026-04-20-real-sap-abap-interview-questions-otc-pricing-odata-btp/Article';
import { meta as meta_2026_04_20_real_sap_abap_interview_questions_otc_pricing_odata_btp } from './2026-04-20-real-sap-abap-interview-questions-otc-pricing-odata-btp/meta';
import Article_2026_04_14_real_frontend_developer_interview_questions_react_typescript_aws_cicd_microfrontend from './2026-04-14-real-frontend-developer-interview-questions-react-typescript-aws-cicd-microfrontend/Article';
import { meta as meta_2026_04_14_real_frontend_developer_interview_questions_react_typescript_aws_cicd_microfrontend } from './2026-04-14-real-frontend-developer-interview-questions-react-typescript-aws-cicd-microfrontend/meta';
import Article_2026_04_10_cloud_operations_engineer_real_interview_questions_azure_aks_sql_gitops from './2026-04-10-cloud-operations-engineer-real-interview-questions-azure-aks-sql-gitops/Article';
import { meta as meta_2026_04_10_cloud_operations_engineer_real_interview_questions_azure_aks_sql_gitops } from './2026-04-10-cloud-operations-engineer-real-interview-questions-azure-aks-sql-gitops/meta';
import Article_2026_02_24_cloud_operations_engineer_real_interview_questions_azure_aks_sql_gitops from './2026-02-24-cloud-operations-engineer-real-interview-questions-azure-aks-sql-gitops/Article';
import { meta as meta_2026_02_24_cloud_operations_engineer_real_interview_questions_azure_aks_sql_gitops } from './2026-02-24-cloud-operations-engineer-real-interview-questions-azure-aks-sql-gitops/meta';
import Article_2026_04_07_cloud_platforms_engineer_real_interview_questions_azure_m365_security_automation from './2026-04-07-cloud-platforms-engineer-real-interview-questions-azure-m365-security-automation/Article';
import { meta as meta_2026_04_07_cloud_platforms_engineer_real_interview_questions_azure_m365_security_automation } from './2026-04-07-cloud-platforms-engineer-real-interview-questions-azure-m365-security-automation/meta';
import Article_2026_04_03_real_enterprise_developer_interview_questions_kubernetes_aws_devops_security_usa_uk_canada_australia from './2026-04-03-real-enterprise-developer-interview-questions-kubernetes-aws-devops-security-usa-uk-canada-australia/Article';
import { meta as meta_2026_04_03_real_enterprise_developer_interview_questions_kubernetes_aws_devops_security_usa_uk_canada_australia } from './2026-04-03-real-enterprise-developer-interview-questions-kubernetes-aws-devops-security-usa-uk-canada-australia/meta';
import Article_2026_04_01_real_enterprise_developer_interview_questions_dotnet_sql_angular_cloud from './2026-04-01-real-enterprise-developer-interview-questions-dotnet-sql-angular-cloud/Article';
import { meta as meta_2026_04_01_real_enterprise_developer_interview_questions_dotnet_sql_angular_cloud } from './2026-04-01-real-enterprise-developer-interview-questions-dotnet-sql-angular-cloud/meta';

export const interviewArticleEntries = [
  { meta: meta_2026_06_11_senior_cloud_engineer_aws_migration_finance_interview_questions, Article: Article_2026_06_11_senior_cloud_engineer_aws_migration_finance_interview_questions },
  { meta: meta_2026_06_02_senior_ai_ml_engineer_interview_questions_recommendation_systems, Article: Article_2026_06_02_senior_ai_ml_engineer_interview_questions_recommendation_systems },
  { meta: meta_2026_05_27_ai_technical_lead_interview_questions_rag_llm_financial_services_compliance, Article: Article_2026_05_27_ai_technical_lead_interview_questions_rag_llm_financial_services_compliance },
  { meta: meta_2026_05_06_real_security_engineer_interview_questions_cloud_security_devsecops_usa, Article: Article_2026_05_06_real_security_engineer_interview_questions_cloud_security_devsecops_usa },
  { meta: meta_2026_05_06_real_azure_architect_interview_questions_solutions_architect_usa, Article: Article_2026_05_06_real_azure_architect_interview_questions_solutions_architect_usa },
  { meta: meta_2026_05_06_real_ai_engineer_interview_questions_llm_agents_rag_system_design_usa, Article: Article_2026_05_06_real_ai_engineer_interview_questions_llm_agents_rag_system_design_usa },
  { meta: meta_2026_04_30_real_enterprise_ai_ml_engineer_interview_questions_rag_llm_genai_mlops, Article: Article_2026_04_30_real_enterprise_ai_ml_engineer_interview_questions_rag_llm_genai_mlops },
  { meta: meta_2026_04_25_real_devops_cloud_engineer_interview_questions_aws_kubernetes_helm_cicd_gitops, Article: Article_2026_04_25_real_devops_cloud_engineer_interview_questions_aws_kubernetes_helm_cicd_gitops },
  { meta: meta_2026_04_20_real_sap_abap_interview_questions_otc_pricing_odata_btp, Article: Article_2026_04_20_real_sap_abap_interview_questions_otc_pricing_odata_btp },
  { meta: meta_2026_04_14_real_frontend_developer_interview_questions_react_typescript_aws_cicd_microfrontend, Article: Article_2026_04_14_real_frontend_developer_interview_questions_react_typescript_aws_cicd_microfrontend },
  { meta: meta_2026_04_10_cloud_operations_engineer_real_interview_questions_azure_aks_sql_gitops, Article: Article_2026_04_10_cloud_operations_engineer_real_interview_questions_azure_aks_sql_gitops },
  { meta: meta_2026_02_24_cloud_operations_engineer_real_interview_questions_azure_aks_sql_gitops, Article: Article_2026_02_24_cloud_operations_engineer_real_interview_questions_azure_aks_sql_gitops },
  { meta: meta_2026_04_07_cloud_platforms_engineer_real_interview_questions_azure_m365_security_automation, Article: Article_2026_04_07_cloud_platforms_engineer_real_interview_questions_azure_m365_security_automation },
  { meta: meta_2026_04_03_real_enterprise_developer_interview_questions_kubernetes_aws_devops_security_usa_uk_canada_australia, Article: Article_2026_04_03_real_enterprise_developer_interview_questions_kubernetes_aws_devops_security_usa_uk_canada_australia },
  { meta: meta_2026_04_01_real_enterprise_developer_interview_questions_dotnet_sql_angular_cloud, Article: Article_2026_04_01_real_enterprise_developer_interview_questions_dotnet_sql_angular_cloud },
] as const;
